name: Flutter CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  FLUTTER_CHANNEL: 'stable'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Flutter Version
        run: |
          FLUTTER_VERSION=$(grep 'sdk: flutter' pubspec.yaml -A 1 | grep 'sdk:' | sed -E 's/.*>=(.*?) .*/\1/')
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Generate Build Number
        id: buildnumber
        run: echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Rename artifacts
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-${{ env.BUILD_NUMBER }}.apk
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-${{ env.BUILD_NUMBER }}.apk
          tag_name: v1.0.${{ env.BUILD_NUMBER }}
          name: Release v1.0.${{ env.BUILD_NUMBER }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
